version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - AUTH_REDIRECT_URL=${AUTH_REDIRECT_URL}
      - DB_URL=${DB_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pizzashop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: